#!/usr/bin/env python3
"""PreToolUse gate guard for the government-recompete-monitor repo.

Blocks a fixed set of high-risk git/gh operations UNLESS a VALID, BOUND approval
token exists at /home/michael/.gate_approval. Designed to fail CLOSED: any
uncertainty (unparseable input, malformed command, unreadable/malformed gate
file, missing/mismatched/stale binding) results in a DENY for a matched
dangerous command.

Denied without a valid bound approval:
  - git merge ...
  - git push ... origin ... main       (pushing to main)
  - git push ... --force / -f / --force-with-lease   (any force-push)
  - gh pr merge ...
  - git add ... integration/recompete_report.csv

Approval model (channel-neutral):
  The gate file, when present, must be a JSON object -- a bound approval token
  supplied by a separate, Michael-controlled mechanism OUTSIDE Claude. Mere
  existence of the file is NOT sufficient (a stale or incorrectly populated file
  fails closed). Discord is one possible transport for delivering that token but
  is NOT required and is NOT the universally mandatory approval channel. The
  token must bind the exact target and pass provenance checks; anything missing,
  malformed, stale, or mismatched fails closed. Claude never creates, edits, or
  populates this file -- the hook only READS it.

Required, non-empty token fields (see _authorization_valid for full semantics):
  repo, operation, base_sha, head_sha, scope, approved_by, provenance,
  expires_at  (+ method for merge/publication operations; + branch for a PR
  merge). Provenance must be human and NOT model-/prompt-generated: a prompt
  generated by Claude or ChatGPT is never approval, and Claude can never
  self-authorize.

Non-matching commands and non-Bash tools pass through untouched (exit 0, no
output) so the normal Claude Code permission flow still applies.

Protocol: reads the PreToolUse JSON payload on stdin, emits a
hookSpecificOutput.permissionDecision of "deny" to block. Silence + exit 0 is a
pass-through (NOT a force-allow), so other permission rules remain in effect.
"""
import sys
import os
import re
import json
import time
import subprocess
from datetime import datetime, timezone

# Approval file path. Defaults to the production location and is overridable via
# GATE_APPROVAL_PATH only to give tests a controlled, guaranteed-absent path
# (subprocess-invoked, so it cannot be monkeypatched in-process). When the env
# var is unset -- i.e. in production -- behavior is identical to the hardcoded
# path, and the gate still fails CLOSED.
GATE = os.environ.get("GATE_APPROVAL_PATH", "/home/michael/.gate_approval")

# The sole human approval authority. Michael is the only authority; this is a
# label the bound token must carry, overridable only to let tests assert the
# authority binding without hardcoding host state. Never a secret.
AUTHORITY = os.environ.get("GATE_APPROVAL_AUTHORITY", "michael").strip().lower()

# A generated prompt (from Claude, ChatGPT, or any model) is NEVER approval, and
# Claude can never self-authorize. Any of these provenance sources fails closed.
MODEL_SOURCES = {
    "claude", "chatgpt", "gpt", "openai", "anthropic", "assistant", "ai",
    "model", "llm", "generated", "prompt", "self",
}

# (compiled regex, human label). Patterns are matched against a single command
# segment (see _segments) with whitespace normalized. Over-blocking is the safe
# direction for a fail-closed gate, so patterns are deliberately broad.
PATTERNS = [
    (re.compile(r"\bgit\s+merge\b"), "git merge"),
    (re.compile(r"\bgit\s+push\b.*\borigin\b.*\bmain\b"), "git push origin main"),
    (re.compile(r"\bgit\s+push\b.*(--force-with-lease|--force\b|(^|\s)-f\b)"), "force-push"),
    (re.compile(r"\bgh\s+pr\s+merge\b"), "gh pr merge"),
    (re.compile(r"\bgit\s+add\b.*integration/recompete_report\.csv\b"),
     "git add integration/recompete_report.csv"),
]

# Local operations whose bound head SHA is the working tree's current HEAD.
_LOCAL_HEAD_OPS = {"git merge", "git push origin main", "force-push"}
# Operations that publish/merge and therefore MUST bind a merge/publication method.
_MERGE_OPS = {"git merge", "gh pr merge"}

# Base binding fields every token must carry (non-empty).
_REQUIRED_FIELDS = (
    "repo", "operation", "base_sha", "head_sha", "scope",
    "approved_by", "provenance", "expires_at",
)


def _emit_deny(reason):
    """Emit a PreToolUse deny decision and exit 0 (the decision is in the JSON)."""
    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "deny",
            "permissionDecisionReason": reason,
        }
    }))
    sys.exit(0)


def _passthrough():
    """No decision: let the normal permission flow handle this command."""
    sys.exit(0)


def _segments(command):
    """Split a shell command into rough segments on separators/operators so a
    match in one clause isn't diluted by unrelated text elsewhere."""
    parts = re.split(r"(?:&&|\|\||[;&|\n])", command)
    return [" ".join(p.split()) for p in parts if p.strip()]


def _git(cwd, *args):
    """Run a read-only git query in ``cwd``; return stripped stdout or None.

    Never mutates anything (callers only use rev-parse/config). Any failure
    (not a repo, missing ref, git absent) returns None so the caller fails
    CLOSED."""
    try:
        out = subprocess.run(
            ["git", "-C", cwd, *args],
            capture_output=True, text=True, timeout=10,
        )
    except Exception:
        return None
    if out.returncode != 0:
        return None
    return out.stdout.strip()


def _repo_identity(cwd):
    """Return the ``owner/repo`` identity from origin, or None if undeterminable."""
    url = _git(cwd, "config", "--get", "remote.origin.url")
    if not url:
        return None
    url = url.strip()
    # git@github.com:owner/repo(.git)  |  https://github.com/owner/repo(.git)
    m = re.search(r"[:/]([^/:]+/[^/]+?)(?:\.git)?/?$", url)
    return m.group(1) if m else None


def _parse_expiry(value):
    """Parse an expiry as epoch seconds (int/float) or ISO-8601; None if bad."""
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        return float(value)
    if isinstance(value, str):
        try:
            dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
        except ValueError:
            return None
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt.timestamp()
    return None


def _parsed_merge_method(command):
    """Best-effort merge method from a `gh pr merge` command; None if unspecified."""
    if re.search(r"(?:^|\s)(?:-s|--squash)\b", command):
        return "squash"
    if re.search(r"(?:^|\s)--rebase\b", command):
        return "rebase"
    if re.search(r"(?:^|\s)--merge\b", command):
        return "merge"
    return None


def _parsed_pr_number(command):
    """Best-effort PR number from a `gh pr merge <N>` command; None if absent."""
    m = re.search(r"\bgh\s+pr\s+merge\s+(?:.*?\s)?(\d+)\b", command)
    return m.group(1) if m else None


def _load_token(path):
    """Read+parse the gate file as a JSON dict; None on any problem (fail closed)."""
    try:
        with open(path, "r", encoding="utf-8") as fh:
            data = json.load(fh)
    except Exception:
        return None
    return data if isinstance(data, dict) else None


def _authorization_valid(matched_label, command, cwd):
    """Return (ok, reason). ok=True ONLY when a complete, current, human-issued,
    correctly-bound approval token authorizes exactly this operation.

    Every failure mode -- absent/malformed file, missing or empty binding, wrong
    authority, model-/prompt-generated provenance, operation/repo/PR/method/scope
    mismatch, SHA drift, or stale expiry -- returns ok=False (fail closed)."""
    token = _load_token(GATE)
    if token is None:
        return False, "no valid bound approval token present"

    # 1. Completeness -- every required binding present and non-empty.
    required = list(_REQUIRED_FIELDS)
    if matched_label in _MERGE_OPS:
        required.append("method")
    if matched_label == "gh pr merge":
        required.append("branch")
    for field in required:
        value = token.get(field)
        if value is None or (isinstance(value, (str, list, dict)) and len(value) == 0):
            return False, f"incomplete authorization binding: '{field}' missing/empty"
    if not (isinstance(token["scope"], list) and all(isinstance(s, str) for s in token["scope"])):
        return False, "incomplete authorization binding: 'scope' must be a non-empty list of paths"

    # 2. Sole authority -- Michael only.
    if str(token.get("approved_by", "")).strip().lower() != AUTHORITY:
        return False, "authorization not issued by the sole approval authority"

    # 3. Provenance -- human, and never a model/prompt-generated authorization.
    prov = token.get("provenance")
    if not isinstance(prov, dict):
        return False, "authorization lacks structured human provenance"
    source = str(prov.get("source", "")).strip().lower()
    if source in MODEL_SOURCES or prov.get("generated") is True:
        return False, "model-/prompt-generated text is never valid approval"
    if not prov.get("human"):
        return False, "authorization lacks verified human provenance"

    # 4. Operation binding -- must name exactly this matched operation.
    if str(token.get("operation", "")).strip() != matched_label:
        return False, "operation binding mismatch"

    # 5. Repository binding -- must name exactly this repository.
    actual_repo = _repo_identity(cwd)
    if actual_repo is None:
        return False, "cannot determine repository identity to verify binding"
    if str(token.get("repo", "")).strip() != actual_repo:
        return False, "repository binding mismatch"

    # 6. Freshness -- stale/expired approval fails closed.
    expiry = _parse_expiry(token.get("expires_at"))
    if expiry is None:
        return False, "unparseable authorization expiry"
    if expiry <= time.time():
        return False, "authorization expired/stale"

    # 7. Base SHA binding -- must match the live base ref (drift invalidates).
    base_ref = str(token.get("base_ref", "origin/main")).strip() or "origin/main"
    actual_base = _git(cwd, "rev-parse", base_ref)
    if actual_base is None:
        return False, f"cannot resolve base ref '{base_ref}' to verify binding"
    if str(token.get("base_sha", "")).strip() != actual_base:
        return False, "base SHA binding mismatch (base moved since approval)"

    # 8. Head SHA binding -- oracle depends on the operation.
    if matched_label in _LOCAL_HEAD_OPS:
        actual_head = _git(cwd, "rev-parse", "HEAD")
        if actual_head is None:
            return False, "cannot resolve HEAD to verify binding"
        if str(token.get("head_sha", "")).strip() != actual_head:
            return False, "head SHA binding mismatch (HEAD moved since approval)"
    elif matched_label == "gh pr merge":
        actual_head = _git(cwd, "rev-parse", f"origin/{str(token['branch']).strip()}")
        if actual_head is None:
            return False, "cannot resolve PR branch head to verify binding"
        if str(token.get("head_sha", "")).strip() != actual_head:
            return False, "head SHA binding mismatch (PR branch moved since approval)"

    # 9. PR + method binding for a PR merge.
    if matched_label == "gh pr merge":
        parsed_pr = _parsed_pr_number(command)
        if parsed_pr is not None and str(token.get("pr", "")).strip() != parsed_pr:
            return False, "PR binding mismatch"
        parsed_method = _parsed_merge_method(command)
        if parsed_method is not None and str(token.get("method", "")).strip().lower() != parsed_method:
            return False, "merge-method binding mismatch"

    # 10. Scope binding -- a gated `git add <path>` must be within approved scope.
    if matched_label.startswith("git add"):
        path_in_cmd = "integration/recompete_report.csv"
        if path_in_cmd not in token["scope"]:
            return False, "changed-file scope mismatch"

    return True, "authorized"


def main():
    raw = sys.stdin.read()
    try:
        data = json.loads(raw)
    except Exception:
        # Cannot see the command at all -> cannot certify it safe. Fail closed.
        _emit_deny("gate-guard: unparseable PreToolUse payload; failing closed.")

    # json.loads can return a non-dict (array, string, number, bool, null).
    # A non-dict has no .get(), so certifying it safe is impossible. Fail closed.
    if not isinstance(data, dict):
        _emit_deny("gate-guard: PreToolUse payload is not a dict; failing closed.")

    if data.get("tool_name") != "Bash":
        _passthrough()

    # tool_input may be absent or an unexpected type; only a dict can carry a
    # command we can inspect. Anything else -> no usable command -> fail closed
    # below via the string check.
    tool_input = data.get("tool_input")
    if not isinstance(tool_input, dict):
        tool_input = {}
    command = tool_input.get("command")
    if not isinstance(command, str):
        _emit_deny("gate-guard: missing/malformed Bash command; failing closed.")

    matched = None
    for seg in _segments(command):
        for pattern, label in PATTERNS:
            if pattern.search(seg):
                matched = label
                break
        if matched:
            break

    if matched is None:
        _passthrough()

    # A dangerous op was matched. The ONLY way through is a complete, current,
    # human-issued, correctly-bound approval token. Prefer the payload cwd (the
    # command's actual working directory) so bindings verify against the right
    # repository; fall back to the hook's own cwd.
    cwd = data.get("cwd")
    if not isinstance(cwd, str) or not cwd:
        cwd = os.getcwd()

    ok, reason = _authorization_valid(matched, command, cwd)
    if ok:
        # Approval present and fully bound. Pass through (do not force-allow) so
        # other rules still apply; the operator has explicitly authorized this.
        _passthrough()

    _emit_deny(
        f"gate-guard: '{matched}' blocked without valid Michael-issued authorization "
        f"({reason}). Provide a complete, current, correctly-bound approval token at "
        f"{GATE} via any Michael-controlled channel (Discord is optional, not required). "
        f"Claude may not create or populate it. Failing closed."
    )


if __name__ == "__main__":
    main()
