-- migrations/020_lead_intelligence.sql
-- Lead Intelligence: imported sales prospects and their contract matches.
-- Idempotent: IF NOT EXISTS guards make it safe to re-run.
CREATE TABLE IF NOT EXISTS lead_companies (
    id                        SERIAL PRIMARY KEY,
    company_name              TEXT NOT NULL,
    contact_name              TEXT,
    contact_title             TEXT,
    phone                     TEXT,
    email                     TEXT,
    company_location          TEXT,
    state                     TEXT,
    website                   TEXT,
    service_notes             TEXT,
    contact_type              TEXT,
    source_notes              TEXT,
    inferred_service_category TEXT,
    federal_experience_signal INTEGER NOT NULL DEFAULT 0,
    likely_customer_score     INTEGER NOT NULL DEFAULT 0,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(company_name)
);
CREATE INDEX IF NOT EXISTS idx_lead_companies_score
    ON lead_companies(likely_customer_score DESC);
CREATE TABLE IF NOT EXISTS lead_contract_matches (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_company_id   INTEGER NOT NULL REFERENCES lead_companies(id) ON DELETE CASCADE,
    internal_id       TEXT NOT NULL,
    match_score       INTEGER NOT NULL DEFAULT 0,
    state_score       INTEGER NOT NULL DEFAULT 0,
    service_score     INTEGER NOT NULL DEFAULT 0,
    timing_score      INTEGER NOT NULL DEFAULT 0,
    value_score       INTEGER NOT NULL DEFAULT 0,
    federal_fit_score INTEGER NOT NULL DEFAULT 0,
    match_reason      TEXT,
    outreach_angle    TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(lead_company_id, internal_id)
);
CREATE INDEX IF NOT EXISTS idx_lead_matches_company
    ON lead_contract_matches(lead_company_id);
